### ISSUE TITLE
Fix seed.js and add migrate to add correct columns for cohort

### ISSUE THREAD

**Issue by sebgro98** [boolean-uk/team-dev-server-ex-2410-team3#22]
Updating the seed.js file to take into account the new changes in the prisma schema to this issue: https://github.com/orgs/boolean-uk/projects/21/views/2?pane=issue&itemId=85065792&issue=boolean-uk%7Cteam-dev-server-ex-2410-team3%7C9

```
async function createCohort() {
  const cohort = await prisma.cohort.create({
    data: {
      name: 'Web Development',
      startDate: new Date('2014-06-01'),
      endDate: new Date('2014-12-01'),
      createdAt: new Date(),
      updatedAt: new Date()
    }
  })

  console.info('Cohort created', cohort)

  return cohort
}

```
Also updating the migration to create the tables with the correct columns

**Comment by Badde00** [comment]
Approved
