### ISSUE TITLE
Fix JSON format bug

### ISSUE THREAD

**Issue by FredrikEH** [boolean-uk/team-dev-server-ex-2410-team3#37]
Right now there is a bug from the backend that changed how the response we get back from a post looks like 

right now we're mapping 
```
{posts.map((post) => {
        return (
          <Post
            key={post.id}
            name={`${post.author.firstName} ${post.author.lastName}`}
            date={post.createdAt}
            content={post.content}
            comments={post.comments}
          />
        );
      })}
```
But the response has a post array and inside that array posts objects and that post object has an author field so to get the correct post we would need to change to

```
{posts.map((post) => {
        return (
          <Post
            key={post.post.id}
            name={`${post.post.author.firstName} ${post.post.author.lastName}`}
            date={post.post.createdAt}
            content={post.post.content}
            comments={post.post.comments}
          />
        );
      })}
```

This is not the solution i would do though as that means we might need to change at more places in the frontend I would suggest to change back to the old response structure from the backend instead. Another problem i found was that inside the domain/post.js file on line 42 we have 

```
 firstname: this.user.profile?.firstName,
```
which needs to be changed to 
```
firstName: this.user.profile?.firstName,
```

Edit
This issue aims to fix this bug by changing the toJSON() function. Currently this function returns a JSON object named post, which is not required and is the cause of this bug. 

We intend to change the JSONformat so it goes from this:

    return {
      post: {                                                              <--------------------- (This post wrapper is causing the post.post bug)
        id: this.id,
        content: this.content,
        createdAt: this.createdAt,
        updatedAt: this.updatedAt,
        author: {
          id: this.user.id,
          cohortId: this.user.cohortId,
          role: this.user.role,
          firstname: this.user.profile?.firstName,
          lastName: this.user.profile?.lastName,
          bio: this.user.profile?.bio,
          githubUrl: this.user.profile?.githubUrl,
          profileImageUrl: this.user.profile?.profileImageUrl
        }
      }
    }

To this:
{
  "status": "success",
  "data": {
    "id": 0,
    "content": "My first post!",
    "createdAt": "2024-10-30T13:43:38.440Z",
    "updatedAt": "2024-10-30T13:43:38.440Z",
    "author": {
      "id": 1,
      "cohortId": 0,
      "role": "string",
      "firstName": "string",
      "lastName": "string",
      "bio": "string",
      "githubUrl": "string",
      "profileImageUrl": "string"
    }
  }
}

**Comment by amos1969** [comment]
I'm not clear what you actually intend to do here. 
- Can you detail the changes you actually intend to make. 
- Do you need to open a related issue and get the backend changed too?

**Comment by amos1969** [comment]
Approved
