### ISSUE TITLE
Backend: Include the users' specialism field in cohort response body

### ISSUE THREAD

**Issue by sebgro98** [boolean-uk/team-dev-server-ex-2410-team3#49]
The front-end cohort page needs to access the users'/teachers' specialism field. Thus, the backend which is generating the responses for the cohorts endpoints must include them, for example with the following code in domain/cohort.js:
```JavaScript
      include: {
        users: {
          select: {
            id: true,
            role: true,
            email: true,
            specialism: true,
            profile: true
          }
        }
      }
```

**Comment by sebgro98** [comment]
Approved

**Comment by amos1969** [comment]
Approved

**Comment by maaxolofsson** [comment]
I accidentally closed this.
