### ISSUE TITLE
API endpoint - POST: Post post

### ISSUE THREAD

**Issue by amos1969** [boolean-uk/team-dev-server-ex-2410-team3#7]
Create a post endpoint with the routing ('/posts'). The "app.post" should take in content from the request body. There should be a function which validates that the field is longer than 3 characters and then create a new post in the database and return a response of 201 if it's successful and a response of 401 if it fails.

no changes made in the prisma model: 
```
model Post {
  id      Int           @id @default(autoincrement())
  content String
  userId  Int
  user    User          @relation(fields: [userId], references: [id])
}
```
the endpoint:

```
app.post('/posts', async (req, res) => {
  const { content } = req.body

  try {
    if (!content || content.length < 3) {
      return res.status(401).json({
        error: 'Content has to be more than 3 characters'
      })
    }
    const newPost = await Post.create({
      content
    })
    res.status(201).json({
      status: 'success',
      data: {
        post: newPost
      }
    })
  } catch (err) {
    res.status(401).json({
      status: 'fail',
      message: err.message
    })
  }
})
```

**Comment by MayraMahamud** [comment]
> If you're modifying the Model you'll need to add stuff to the OpenAPI Spec to make sure it stays in sync. Add the required changes in here and then I'll approve it.

@amos1969 
if im not modifying the model can i just remove the prisma model from the issue?

**Comment by amos1969** [comment]
@MayraMahamud you can leave the model in but make it clear that no changes are required to it. 
I assumed this didn't exist in the Database so would require you to add it in.

**Comment by MayraMahamud** [comment]
> [@MayraMahamud](https://github.com/MayraMahamud) you can leave the model in but make it clear that no changes are required to it. I assumed this didn't exist in the Database so would require you to add it in.

@amos1969 
Okay, fixed it

**Comment by amos1969** [comment]
Approved
